### ISSUE TITLE
Why limiting this to PLUGINS-PREVIEW@2?

### ISSUE THREAD

**Issue by steph643** [grovelabs/meteor-call-async#3]
Great idea! I used to have my own "call2" function with returnStubValue=true, but having this feature in a community package would be definitely better.
But why limiting this to PLUGINS-PREVIEW@2? Those using v1.1.0 can still benefit from returnStubValue=true even though they don't benefit from throwStubExceptions... Is there another reason?

**Comment by lourd** [comment]
:smile: thanks!

Limiting to the recent release because it's designed to be a complete implementation of `Meteor.callAsync`. If people want to use the `returnStubValue` option they'll have to do the arduous task of specifying it themselves :stuck_out_tongue_winking_eye:
